players:

  - name: player1
    robot: False
    werewolf: True
    position:
      - x: 0
        y: 0
        z: 0

  - name: player2
    robot: True
    werewolf: False
    position:
      - x: 0
        y: 0
        z: 0

  - name: player3
    robot: False
    werewolf: False
    position:
      - x: 0
        y: 0
        z: 0

  - name: player4
    robot: False
    werewolf: False
    position:
      - x: 0
        y: 0
        z: 0

  - name: player5
    robot: False
    werewolf: False
    position:
      - x: 0
        y: 0
        z: 0

  - name: player6
    robot: False
    werewolf: False
    position:
      - x: 0
        y: 0
        z: 0

messaging:

  broker_host: "192.168.0.101"
  broker_port: 32777

  # exchanges
  artificial_agent:
  pre_processing:
    update_gaze: "gaze_update"
  environment:
