players:

  - name: player1
    robot: False
    werewolf: True

  - name: player2
    robot: False
    werewolf: False

  - name: player3
    robot: False
    werewolf: False

  - name: player4
    robot: False
    werewolf: False

  - name: player5
    robot: False
    werewolf: False

  - name: player6
    robot: False
    werewolf: False