players:

  - name: player1
    robot: False
    werewolf: True

  - name: player2
    robot: True
    werewolf: False

  - name: player3
    robot: False
    werewolf: False

  - name: player4
    robot: False
    werewolf: False

  - name: player5
    robot: False
    werewolf: False

  - name: player6
    robot: False
    werewolf: False

messaging:

  broker_host: "192.168.0.101"
  broker_port: 32777

  # exchanges
  artificial_agent:
  pre_processing:
    update_gaze: "gaze_update"
  environment: