players:

  - name: player1
    robot: False
    werewolf: True
    position:
      - x: 0
        y: 0
        z: 0

  - name: player2
    robot: True
    werewolf: False
    position:
      - x: 0
        y: 0
        z: 0

  - name: player3
    robot: False
    werewolf: False
    position:
      - x: 0
        y: 0
        z: 0

  - name: player4
    robot: False
    werewolf: False
    position:
      - x: 0
        y: 0
        z: 0

  - name: player5
    robot: False
    werewolf: False
    position:
      - x: 0
        y: 0
        z: 0

  - name: player6
    robot: False
    werewolf: False
    position:
      - x: 0
        y: 0
        z: 0

messaging:

  # broker_host: "192.168.0.108"
  # broker_port: 5672
  # broker_user: "test"
  # broker_pass: "test"
  broker_host: "192.168.43.83"
  broker_port: 32777
  broker_user: "guest"
  broker_pass: "guest"

  # sensor hosts
  mocap_host: "192.168.0.108"

  # exchanges
  artificial_agent: "artificial-agent"
  sensors: "sensors"
  pre_processing: "pre-processor"
  environment: "environment"

  # sensors
  microphone: "microphone"
  camera: "camera"
  kinect: "kinect"
  mocap: "mocap"

  # new sensor
  new_sensor_mocap: "mocap.new_sensor"

  # pre_processing
  mocap_processing: "mocap.processing"
